# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [3]:
def share_bread(N, K):
    x= int(K / N)
    y = K % N
    print(x,y)
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

4 2


## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [5]:
def leap_year(year):
    return 'YOU SHALL NOT PASS'

assert leap_year(5) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [37]:
import math

def amulet_area(a, b, c):
    p = (a+b+c)/2
    S=math.sqrt(p* (p-a)*(p-b)*(p-c))
    return S

assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [55]:
import numpy as np

def cal_euclidean(a, b):    
    distance = np.sqrt(np.sum((a-b)**2))
    return distance

def cal_manhattan(a, b):    
    distance = np.sum(np.abs(a-b))
    return distance

def cal_cosine(a, b):    
    distance = np.sum(a*b) / (np.sqrt(np.sum(a**2)) * np.sqrt(np.sum(b**2)) )
    return distance

In [54]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)

print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

29.34280150224242
77
-0.27322605389402466


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [12]:
import numpy as np
my_array = np.random.rand(1, 100)
max_index = my_array.argmax()
my_array[0][max_index]=1
min_index = my_array.argmin()
my_array[0][min_index]=0
print(np.max(my_array), np.min(my_array))
print(my_array)

1.0 0.0
[[0.0434906  0.86831976 1.         0.66799048 0.0370895  0.71742543
  0.71159419 0.94334595 0.38769034 0.53965477 0.4618922  0.9855496
  0.27283547 0.51507743 0.63509158 0.29059482 0.39814276 0.56649073
  0.77883102 0.93834452 0.70652742 0.3775234  0.57366905 0.08649897
  0.4624168  0.51742092 0.45131372 0.78180931 0.36262394 0.09435237
  0.75127268 0.77937165 0.70831924 0.02751579 0.6989896  0.32075568
  0.12978778 0.41346284 0.4988519  0.13471352 0.95456217 0.47617677
  0.29175614 0.30146934 0.25359992 0.69435972 0.28960304 0.84157899
  0.17645325 0.93522104 0.81486476 0.76050131 0.99208433 0.48141118
  0.8344787  0.89549109 0.07342599 0.58973416 0.98558533 0.12020132
  0.47075273 0.59788445 0.16681084 0.54109916 0.47278868 0.66757603
  0.5240315  0.1333441  0.20846632 0.21948935 0.5527778  0.06214356
  0.75737776 0.87107782 0.25310688 0.83643617 0.45309048 0.72513307
  0.11337829 0.77277462 0.27379632 0.65015598 0.8535007  0.44169171
  0.71357597 0.83040483 0.         0.3485

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [25]:
import numpy as np

my_array = np.random.uniform(low=0., high=50., size=(5,6))
selected_column = np.argmax(my_array.max(axis = 0))

print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print(selected_column)

Shape:  (5, 6)
Array
[[14.64047596 12.83012761 43.04462605 42.84156136 28.32502696 23.06739746]
 [38.93863754 33.72466153 30.44865184  5.12481608 45.05388193 23.19823719]
 [44.66078657 16.31792814  3.9463719  35.01549418 38.57337069  8.45496163]
 [28.70440443 36.17909714 29.74873538 28.21466979 36.90245203 14.67168399]
 [18.72715736 31.70681982 45.53051541  7.54647274  3.66725926 49.50835566]]
5


Напишите функцию, которая принимает на вохд матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [30]:
def get_unique_rows(X):
    X_unique = np.unique(X, axis = 0)
    return X_unique

In [35]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[4 5 4]
 [5 4 5]
 [5 5 5]
 [5 5 4]
 [4 4 4]
 [4 5 4]
 [4 4 5]
 [4 5 4]
 [5 4 4]
 [5 4 5]]


In [36]:
get_unique_rows(X)

array([[4, 4, 4],
       [4, 4, 5],
       [4, 5, 4],
       [5, 4, 4],
       [5, 4, 5],
       [5, 5, 4],
       [5, 5, 5]])